# Generated by Django 4.2 on 2023-09-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psapApp', '0005_appliedforadmissionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMeritData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_university', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=100)),
                ('merit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psapApp.stdinfotable')),
            ],
        ),
    ]
