# Generated by Django 4.2 on 2023-09-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psapApp', '0006_studentmeritdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='stdinfotable',
            name='inter_obtained_marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
