# Generated by Django 4.2 on 2023-09-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psapApp', '0007_testimonial_alter_stdinfotable_inter_obtained_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
