# Generated by Django 4.2 on 2023-12-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psapApp', '0008_remove_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
