# Generated by Django 4.2 on 2023-12-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psapApp', '0011_alter_admission_admission_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='account_number',
            field=models.CharField(default=2332, max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='account_title',
            field=models.CharField(default='shah', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='application_fees',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='bank_name',
            field=models.CharField(default='hbl', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='other_requirements',
            field=models.TextField(null=True),
        ),
    ]
