# Generated by Django 4.2 on 2023-12-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psapApp', '0012_admission_account_number_admission_account_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admission',
            name='account_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
